/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'alex.kiernan' at '12/20/16 10:15 AM' with Gradle 3.2.1
 *
 * @author alex.kiernan, @date 12/20/16 10:15 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
